# Generated by Django 4.2.6 on 2023-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
