# Generated by Django 4.2.6 on 2023-10-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cadastro_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de contato', 'verbose_name_plural': 'Formulários de contatos'},
        ),
    ]
