# Generated by Django 4.2.6 on 2023-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adocoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[(0, 'Cachorro'), (1, 'Gato'), (2, 'Coelho'), (3, 'Tartaruga'), (4, 'Hamster')], max_length=50)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=50)),
                ('historico_de_saúde', models.TextField()),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastro de animal',
                'verbose_name_plural': 'Cadastros de animais',
                'ordering': ['nome'],
            },
        ),
    ]
