# Generated by Django 4.2.6 on 2023-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocoes',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Coelho', 'Coelho'), ('Tartaruga', 'Tartaruga'), ('Hamster', 'Hamster')], max_length=50),
        ),
    ]
