# Generated by Django 4.2.6 on 2023-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_alter_adocoes_especie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adocoes',
            old_name='historico_de_saúde',
            new_name='historico_de_saude',
        ),
        migrations.AddField(
            model_name='adocoes',
            name='foto',
            field=models.ImageField(blank=True, default='media/fotos_pets/1.jpeg', null=True, upload_to='fotos_pets'),
        ),
    ]
